CREATE TABLE IF NOT EXISTS Sport (
NAME TEXT,
SPORT TEXT,
CLASS INTEGER,
COUNTRY TEXT,
MEDAL INTEGER,
RANK INTEGER
)

INSERT INTO Sport VALUES
('PRJJWAL','BADMINTON',5,'INDIA',2,1),
('Kevin','FOOTBALL',5,'Indonesia',3,2),
('James','FOOTBALL',5,'South Korea',8,3),
('Joseph','BADMINTON',5,'INDIA',6,4),
('David','CRICKET',5,'Ivory Coast',5,6);

SELECT * FROM Sport;


SELECT NAME,SPORT,COUNTRY
FROM Sport
WHERE SPORT = 'BADMINTON';

SELECT COUNT(*) AS BadmintonCount
FROM Sport
WHERE SPORT = 'BADMINTON';
